CREATE TABLE pelanggan (
  id_pelanggan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_pelanggan VARCHAR(255) NOT NULL,
  nomor_telepon VARCHAR(20),
  alamat_rumah TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);