CREATE TYPE shift_karyawan AS ENUM ('Pagi', 'Siang', 'Malam');
CREATE TYPE jabatan_enum AS ENUM ('manager', 'kasir', 'operator');

CREATE TABLE karyawan (
  id_karyawan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  no_telepon VARCHAR(20),
  shift shift_karyawan NOT NULL,
  jabatan jabatan_enum NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);