CREATE TABLE item_cucian (
  id_cucian BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pesanan BIGINT REFERENCES pesanan(id_pesanan),
  jenis_pakaian VARCHAR(100) NOT NULL,
  berat_kg DECIMAL(5, 2) NOT NULL,
  kondisi_masuk VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);