CREATE TYPE status_pesanan_enum AS ENUM (
  'Diterima', 
  'Dicuci',
  'selesai dicuci',
  'Disetrika',
  'selesai disetrika',
  'Selesai', 
  'Diambil'
);

CREATE TYPE tipe_pesanan_enum AS ENUM (
  'ambil pesanan',
  'antar pesanan'
);

CREATE TABLE pesanan (
  id_pesanan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pelanggan BIGINT REFERENCES pelanggan(id_pelanggan),
  id_karyawan BIGINT REFERENCES karyawan(id_karyawan),
  tanggal_masuk TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  tanggal_estimasi_selesai TIMESTAMP WITH TIME ZONE,
  tanggal_selesai TIMESTAMP WITH TIME ZONE,
  status_pesanan status_pesanan_enum DEFAULT 'Diterima',
  total_harga DECIMAL(12, 2) DEFAULT 0,
  tipe_pesanan tipe_pesanan_enum,
  catatan TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);